### ISSUE TITLE
Doctrine ORM enable issues

### ISSUE THREAD

**Issue by canni** [KnpLabs/KnpRadBundle-documentation#14]
I've just spent hour digging in google on how to enable doctrine ORM :)

Besides obvious thing like adding it to `composer.json` and enabling bundle in `kernel.yml` I was confused about not working annotations, and confused even more about where to put annotations registry init code, thanks to uncle google I found this post [KnpRad+Doctrine ORM](http://pilvee.com/blog/knpradbundle-configurer-doctrine-orm/) but I think this should be pointed out for users docs :)

I could do a PR but my English isn't well enough to publish it ;)

**Comment by dirtyvader** [comment]
Oh thanks a lot, I thought I was going crazy :)
