### ISSUE TITLE
_vendor thing

### ISSUE THREAD

**Issue by l3pp4rd** [KnpLabs/KnpRadBundle-documentation#2]
Since this is a distribution, maybe its possible to have it in src/Rad directory same as example? example app could be enabled only in dev env

**Comment by l3pp4rd** [comment]
and maybe there could be some issues opened to help you with?

**Comment by everzet** [comment]
it's not distribution, it's bundle, which makes distribution :-) There will be only bundle after release. This project is just for testing. And `_vendor` things is just here to easily update bundle code as we don't have package yet ;-)

**Comment by weaverryan** [comment]
When we make it a new bundle, can we create a new git repo and add the files in a series of commits that make its creation seem epic:

```
Feb 10: 12:00:00
everzet

I slayed the dragon of truth and, as promised by the oracle, he gave me the ancient
secrets of creating the asset pipeline. It's creation was foretold, and my destiny fulfilled.
```

What do you  think? :p

**Comment by docteurklein** [comment]
+1 for @weaverryan proposition :p

**Comment by everzet** [comment]
@weaverryan +100500. Could you write couple of those for us as you're the only one who can do it beautfiull?
