### ISSUE TITLE
Bundles config and kernel.yml not being respected for container rebuild

### ISSUE THREAD

**Issue by weaverryan** [KnpLabs/KnpRadBundle-documentation#3]
Hey guys!

I've noticed that in the `dev` environment, if I make a change to any of my bundle configs or `kernel.yml`, the container is not automatically rebuilt. A quick look at the `meta` file for the container in the cache showed that these files are indeed missing.

Thanks!

**Comment by everzet** [comment]
Good note. Will try to add kernel configuration to the container meta.
