### ISSUE TITLE
A list of ideas & questions

### ISSUE THREAD

**Issue by weaverryan** [KnpLabs/KnpRadBundle-documentation#5]
I know this doesn't make for a good ticket, but I had a collection of ideas - individual issues would suck too! I'll number them, to keep things almost manageable:

1) We reference yui path in vendor, but it's not installed? Maybe we can just add a note that you should add it to composer if you want it? And, what would that entry in composer look like?

2) We should create a link under assetic/filters for how to use these, since just including them here doesn't magically mean that less files are parsed, for example. This will probably be in our docs, because of the asset pipeline.

3) Should we include any config in logger for doing things in "prod"?  For example, like emailing you on an error?

4) What is the @bar in the globals section? Is the "@" a special syntax for something? Am I about to learn something new?

5) Should we include the 404, 403, and 500 templates in the application bundle by default? 

6) When I actually get to using the edition, will I be deleting the `KnpRad` directory and create my own? Is there a way to generate this? Would that generated bundle include my error templates?

7) We should give them a default layout that's responsive, with a sidebar and a top nav to show off the blocks

8) What about a better base Controller? For example, the fact that I can't just type `$this->getEntityManager()` inside a controller is almost criminal! Same with the security context, and probably some other things!

Thanks!

**Comment by everzet** [comment]
1. It's not composer job, imo. Composer is PHP packages management tool.
2. Yes. I will add AsseticPipeline link to them later
3. Yeah, could be cool. At least as commented out section
4. Mapping of specific service (by name) to the specific twig variable? (Don't sure it is supported and will work though :-D)
5. Could be awesome
6. There will be project generator script with couple of arguments, which will either generate project with `KnpRad` example OR simple skeleton (just `view/layout.html.twig`, empty `config/routing.yml` ?)
7. Not sure about top nav and blocks as it really-really depends on the project being developed. But we will generate HTML5 Boilerplate as layout at start
8. YES. Have thought and talked about it, but haven't got time to get into it. BTW, `$this->getEntityManager()` is not really as awesome as `$this->getRepository(...)` ;-)

**Comment by everzet** [comment]
Done everything except error pages, but they are in my personal todo ;-)
